using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace CBO.InterestBankLendingRates
{
    public class InterestBankLendingRateManager : InterestBankLendingRateManagerBase
    {
        //<suite-custom-code-autogenerated>
        public InterestBankLendingRateManager(IInterestBankLendingRateRepository interestBankLendingRateRepository)
            : base(interestBankLendingRateRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}