using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;

namespace CBO.InterestBankLendingRates
{
    public class InterestBankLendingRatesAppService : InterestBankLendingRatesAppServiceBase, IInterestBankLendingRatesAppService
    {
        //<suite-custom-code-autogenerated>
        public InterestBankLendingRatesAppService(IInterestBankLendingRateRepository interestBankLendingRateRepository, InterestBankLendingRateManager interestBankLendingRateManager)
            : base(interestBankLendingRateRepository, interestBankLendingRateManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}